// Chart Draw — Terms of Service (English)
// ⚠️ Never edit the body of a version that has taken effect — it is an archived record.
//    To revise, add a new const and append a new entry to the array.
//    (Exception: corrections made before launch while zero users are bound. Not after.)
//    2026-07-22: corrected the v1.0 body under this exception, before launch — Daily Ranking,
//    scope of use, and the ChartDraw name. No new version was published, because publishing one
//    would fabricate an amendment history for users who never existed.
// Paid services remain out of scope. Add them in a new version when payments ship.

const V1_0 = `
These Terms govern your use of ChartDraw (the "Service"), operated by
Lindy Operation Inc. (the "Company").

- **Company**: Lindy Operation Inc. (주식회사 린디오퍼레이션)
- **Representative**: Daehun Lee
- **Business Registration No.**: 193-87-03843
- **Address**: 808-A128, Yueun Tower 3, 1092 Gyeongui-ro, Paju-si, Gyeonggi-do, Republic of Korea
- **Contact**: danny@lindyoperation.com

> This English text is provided for convenience. In the event of any conflict
> between this translation and the Korean version, **the Korean version prevails**.

---

## Article 1 (Purpose)

These Terms set out the rights, obligations, and responsibilities of the Company and
users in connection with the use of the Service.

## Article 2 (Definitions)

① "Service" means ChartDraw and all related services provided by the Company through
mobile applications and other channels.

② "User" means anyone who uses the Service under these Terms, including both Members
and Non-members.

③ "Member" means a user who has created an account.

④ "Non-member" means a user who uses the Service without an account.

⑤ "Learning Records" means the quiz results, scores, accuracy rates, and participation
history generated by a user through the Service.

⑥ "Daily Ranking" means the feature that compares the scores of Members who solved the
same set of questions on a given date and displays a rank and a top percentile.

⑦ "Display Name" means the name **generated and assigned automatically by the Company**
to identify a Member on the Daily Ranking. Users cannot enter or change it, and it does not
reveal a user's real name or email address. However, because a Display Name is linked to a
Member's account, it constitutes personal data and is protected under the Privacy Policy.

## Article 3 (Posting and Amendment of Terms)

① The Company posts these Terms within the Service or on its website
(lindyoperation.com) so that users may review them at any time.

② The Company may amend these Terms to the extent that such amendment does not violate
applicable law.

③ When amending these Terms, the Company will announce the effective date and the reason
for the amendment within the Service or on its website **at least 7 days before** the
effective date. For amendments that are disadvantageous to users or otherwise material,
the announcement will be made **at least 30 days in advance**, and Members will be
notified individually by email or equivalent means.

④ A user who does not agree to the amended Terms may terminate the service agreement
before the effective date. Continued use of the Service after the effective date is
deemed acceptance of the amended Terms.

⑤ Superseded versions remain available on the Company's website, organized by effective
date.

## Article 4 (Description of the Service)

① The Service is an **educational game based on historical stock price charts**. It
displays part of a real historical price series and, when the user identifies the chart
pattern that follows, reveals the hidden portion together with computed facts about that
period.

② The Service does **not** provide any of the following:

- Trading, brokerage, arrangement, or agency of financial investment products
- Investment advice, discretionary investment management, or solicitation to invest
- Real-time market quotations
- Trading functionality involving real funds

③ All features of the Service are **provided free of charge**, and the Service contains no
payment functionality. If the Company later introduces paid features, it will amend these
Terms and give advance notice in accordance with Article 3.

④ The scope of use depends on whether you are signed in:

| Feature | Without an account | Signed in |
|---|---|---|
| The five questions provided each day | Available | Available |
| Pattern book (list and descriptions) | Available | Available |
| All questions | Not available | Available |
| Case questions within the pattern book | Not available | Available |
| Storing Learning Records on the device | Available | Available |
| Learning Records screen (accuracy by pattern, weak patterns) | Not available | Available |
| Keeping Learning Records in your account and continuing across devices | Not available | Available |
| Daily Ranking | Not available | Available |

⑤ **The five questions provided each day are available without an account.** If the
Company narrows this scope, it will give advance notice in accordance with Article 3.

## Article 5 (Formation of the Agreement)

① For Non-members, the agreement is formed when the user installs the application and
uses the Service, at which point the user is deemed to have accepted these Terms.

② For Members, the agreement is formed when the user accepts these Terms, applies to
create an account, and the Company approves the application.

③ The Company may refuse an application, or subsequently terminate the agreement, in any
of the following cases:

- The applicant has used another person's name or information
- The applicant has previously been restricted for violating these Terms
- The application is clearly intended to interfere with the normal operation of the
  Service

## Article 6 (Account Management)

① Members must not allow any third party to use their account credentials.

② If a Member becomes aware that their account has been compromised or is being used by a
third party, the Member must immediately notify the Company and follow its instructions.

③ The Company is liable for damage arising from its failure to take necessary measures
after receiving a notice under Paragraph 2.

## Article 7 (Withdrawal and Restriction of Use)

① A Member may request account deletion at any time through a function provided within
the Service. The Company will delete the Member's personal data and Learning Records
without undue delay, except where retention is required by applicable law.

② Learning Records and Daily Ranking records stored on the server cannot be recovered
after account deletion.

③ Where a user violates these Terms or applicable law, the Company may restrict use of
the Service after prior notice. In urgent cases, notice may be given after the fact.

## Article 8 (Provision, Modification, and Suspension of the Service)

① The Service is, in principle, provided year-round without interruption.

② The Company may change the content, structure, questions, and features of the Service.
Material changes that are disadvantageous to users will be announced in advance in
accordance with Article 3 (3).

③ The Company may temporarily suspend all or part of the Service in the following cases,
and will announce the suspension afterwards where advance notice is impracticable:

- System inspection, maintenance, or replacement
- Force majeure such as power failure, equipment failure, or excessive traffic
- Interruption of third-party services required to operate the Service (app stores,
  cloud infrastructure, and the like)

## Article 9 (Learning Records and Data)

① Learning Records of Non-members are stored solely on the user's device and cannot be
recovered once the application is deleted or the reset function within the Service is
used.

② Learning Records of Members are stored on the Company's servers and are synchronized
across devices signed in to the same account.

③ The processing of personal data is governed by the separate **Privacy Policy**.

## Article 9-2 (Daily Ranking)

① The Daily Ranking is available to Members only. All users receive the same questions on
a given date, and Members' scores are compared to display a rank and a top percentile.
**Taking part is optional; declining does not restrict any other feature.**

② A ranking entry is created **only when a Member actively submits it within the Service.**
Signing in alone does not enter you into the ranking.

③ **Once you submit an entry, your Display Name, score, and rank become visible to other
users of the Service.** The Display Name is generated automatically by the Company and does
not reveal your real name or email address. Users cannot enter or change it. Only the
Display Name, score, and rank are disclosed; email addresses and account identifiers are
never provided to other users.

④ Scores are calculated by the Company's server from the number of attempts you submit for
each question. Users cannot submit or modify a score value directly.

⑤ A ranking entry may be submitted **once per day**, and its score cannot be modified
afterwards. However, a Member may at any time request that the entry be **withdrawn from
display and deleted** from [Settings] within the Service, and the Company will act without
undue delay. Deleting your account also deletes your ranking records.

⑥ A given day's entry may be submitted only on that date and until 03:00 (Korea Standard
Time) on the following day.

⑦ The Daily Ranking exists to encourage participation in learning. The Company offers no
monetary reward or prize in connection with it. Because the Service's questions and
answers are distributed within the application, the Company does not warrant that every
user's score accurately reflects their ability.

⑧ The Company may restrict a Member's participation in the ranking in the following cases.
In such cases the Company shall notify the Member of the reason and scope of the
restriction, and the Member may object to it.

- Submitting or attempting to submit a score by improper means
- Creating multiple accounts for the purpose of participating in the ranking
- Accessing the ranking feature by automated means

## Article 10 (Content and Data Sources)

① The historical price data used in the Service is constructed from the Financial Services
Commission's "Stock Price Information" dataset published on the Korean Public Data Portal,
and consists of historical daily prices based on previous-day closing prices.

② The Company does not warrant the accuracy, completeness, or timeliness of such data and
is not liable for consequences arising from errors in, or discontinuation of, the source
data.

③ Company names and ticker names shown in the Service are used to identify facts as of the
relevant period and do not imply any affiliation, sponsorship, or endorsement between
those companies and the Company.

## Article 11 (Not Investment Advice)

① All content in the Service is provided for **educational and informational purposes**
only and does not constitute a solicitation to buy or sell any financial investment
product, nor advice regarding investment decisions.

② Past chart patterns do not predict future prices. The patterns and cases presented in
the Service do not indicate the future value of any particular security.

③ Investment decisions and their outcomes rest entirely with the user.

## Article 12 (Intellectual Property)

① Rights in the Service and in the software, screen designs, question sets, explanatory
text, and trademarks contained in it belong to the Company.

② Rights in the question database compiled by the Company are protected under the Korean
Copyright Act. Users may not reproduce, distribute, or transmit it, or repeatedly and
systematically extract a substantial part of the database, without the Company's prior
written consent.

③ Users may use the Service for personal, non-commercial purposes only.

## Article 13 (User Obligations)

Users must not:

- Reverse engineer, decompile, or disassemble the Service, or extract its source code
- Access the Service by automated means or harvest data in bulk
- Reproduce, distribute, or commercially exploit the Service's content without permission
- Misappropriate or improperly use another person's account
- Submit Daily Ranking scores by improper means, or create multiple accounts for the
  purpose of participating in the ranking
- Interfere with the stable operation of the Service
- Otherwise violate applicable law

## Article 14 (Limitation of Liability)

① The Company is relieved of liability where it cannot provide the Service due to causes
beyond its reasonable control, such as natural disaster, war, power failure, or an
interruption of telecommunications services.

② The Company is not liable for service disruptions attributable to the user.

③ The Company is not liable for a user's failure to achieve the learning outcomes they
expected from the Service.

④ Nothing in these Terms excludes or limits the Company's liability for damage caused by
its **intent or gross negligence**, or any other liability that cannot be excluded or
limited under applicable law.

## Article 15 (Dispute Resolution)

① The Company and users will seek to resolve disputes arising from use of the Service
through good-faith consultation.

② Where consultation fails, any action shall be brought before the court having
jurisdiction under the Korean Civil Procedure Act.

③ These Terms and use of the Service are governed by the laws of the Republic of Korea.

---

**Addendum**

These Terms take effect on July 21, 2026.

`


export const CHART_DRAW_TERMS_EN = [
  {
    version: '1.0',
    effective: '2026-07-21',
    summary: 'Initial publication',
    body: V1_0,
  },
]
