// Chart Draw — Terms of Service (English)
// ⚠️ Never edit the body of a version that has taken effect — it is an archived record.
//    To revise, add a new const and append a new entry to the array.

const V1_0 = `
These Terms govern your use of Chart Draw (the "Service"), operated by
Lindy Operation Inc. (the "Company").

- **Company**: Lindy Operation Inc. (주식회사 린디오퍼레이션)
- **Representative**: Daehun Lee
- **Business Registration No.**: 193-87-03843
- **Address**: 808-A128, Yueun Tower 3, 1092 Gyeongui-ro, Paju-si, Gyeonggi-do, Republic of Korea
- **Contact**: danny@lindyoperation.com

> This English text is provided for convenience. In the event of any conflict
> between this translation and the Korean version, **the Korean version prevails**.

---

## Article 1 (Purpose)

These Terms set out the rights, obligations, and responsibilities of the Company and
users in connection with the use of the Service.

## Article 2 (Definitions)

① "Service" means Chart Draw and all related services provided by the Company through
mobile applications and other channels.

② "User" means anyone who uses the Service under these Terms, including both Members
and Non-members.

③ "Member" means a user who has created an account.

④ "Non-member" means a user who uses the Service without an account.

⑤ "Paid Service" means any feature, content, or subscription offered by the Company for
a fee.

⑥ "Learning Records" means the quiz results, scores, accuracy rates, and participation
history generated by a user through the Service.

## Article 3 (Posting and Amendment of Terms)

① The Company posts these Terms within the Service or on its website
(lindyoperation.com) so that users may review them at any time.

② The Company may amend these Terms to the extent that such amendment does not violate
applicable law.

③ When amending these Terms, the Company will announce the effective date and the reason
for the amendment within the Service or on its website **at least 7 days before** the
effective date. For amendments that are disadvantageous to users or otherwise material,
the announcement will be made **at least 30 days in advance**, and Members will be
notified individually by email or equivalent means.

④ A user who does not agree to the amended Terms may terminate the service agreement
before the effective date. Continued use of the Service after the effective date is
deemed acceptance of the amended Terms.

⑤ Superseded versions remain available on the Company's website, organized by effective
date.

## Article 4 (Description of the Service)

① The Service is an **educational game based on historical stock price charts**. It
displays part of a real historical price series and, when the user identifies the chart
pattern that follows, reveals the hidden portion together with computed facts about that
period.

② The Service does **not** provide any of the following:

- Trading, brokerage, arrangement, or agency of financial investment products
- Investment advice, discretionary investment management, or solicitation to invest
- Real-time market quotations
- Trading functionality involving real funds

③ The Company may offer parts of the Service free of charge and other parts as Paid
Services.

## Article 5 (Formation of the Agreement)

① For Non-members, the agreement is formed when the user installs the application and
uses the Service, at which point the user is deemed to have accepted these Terms.

② For Members, the agreement is formed when the user accepts these Terms, applies to
create an account, and the Company approves the application.

③ The Company may refuse an application, or subsequently terminate the agreement, in any
of the following cases:

- The applicant has used another person's name or information
- The applicant has previously been restricted for violating these Terms
- The application is clearly intended to interfere with the normal operation of the
  Service

## Article 6 (Account Management)

① Members must not allow any third party to use their account credentials.

② If a Member becomes aware that their account has been compromised or is being used by a
third party, the Member must immediately notify the Company and follow its instructions.

③ The Company is liable for damage arising from its failure to take necessary measures
after receiving a notice under Paragraph 2.

## Article 7 (Withdrawal and Restriction of Use)

① A Member may request account deletion at any time through a function provided within
the Service. The Company will delete the Member's personal data and Learning Records
without undue delay, except where retention is required by applicable law.

② Learning Records stored on the server cannot be recovered after account deletion.

③ Where a user violates these Terms or applicable law, the Company may restrict use of
the Service after prior notice. In urgent cases, notice may be given after the fact.

## Article 8 (Provision, Modification, and Suspension of the Service)

① The Service is, in principle, provided year-round without interruption.

② The Company may change the content, structure, questions, and features of the Service.
Material changes that are disadvantageous to users will be announced in advance in
accordance with Article 3 (3).

③ The Company may temporarily suspend all or part of the Service in the following cases,
and will announce the suspension afterwards where advance notice is impracticable:

- System inspection, maintenance, or replacement
- Force majeure such as power failure, equipment failure, or excessive traffic
- Interruption of third-party services required to operate the Service (app stores,
  cloud infrastructure, and the like)

④ If the Company discontinues a Paid Service, it will refund amounts corresponding to the
remaining period or remaining quantity that the user has paid for but not received.

## Article 9 (Paid Services and Payment)

① The types, contents, prices, and periods of Paid Services are displayed on the purchase
screen within the Service.

② Payment for Paid Services is made **exclusively through the in-app purchase systems of
the Apple App Store or Google Play**. Payment processing and payment-method management
are governed by the policies and procedures of the respective store operator.

③ Subscription-based Paid Services renew automatically in accordance with the policies of
the respective store unless cancelled by the user. Users may cancel directly through the
subscription management screen of the relevant store; cancelling before the next renewal
date prevents charges for the following period.

④ Cancellation of a subscription already paid for takes effect at the end of the remaining
paid period, during which the user may continue to use the Service.

⑤ Where a minor has made a payment without the consent of their legal representative, the
minor or their legal representative may cancel that payment in accordance with applicable
law.

## Article 10 (Withdrawal of Subscription and Refunds)

① Under the Act on Consumer Protection in Electronic Commerce, users may withdraw their
purchase within **7 days** of the payment date.

② However, withdrawal is restricted in the following cases pursuant to Article 17 (2) of
that Act. The Company clearly discloses this on the purchase screen:

- Where provision of the digital content has begun. Where the content consists of
  divisible units, withdrawal remains available for units not yet provided.
- Where the value of the content has significantly diminished through the user's use or
  partial consumption

③ For Paid Services falling under Paragraph 2, the Company provides core functionality
free of charge before purchase so that users can assess the nature of the Service in
advance.

④ Refunds for transactions made through in-app purchase are handled according to the
refund policies and procedures of the respective store operator. Users may also request a
refund from the Company (danny@lindyoperation.com), and the Company will process such
requests in accordance with applicable law.

⑤ If a user is unable to use a Paid Service due to a cause attributable to the Company,
the Company will refund the amount corresponding to that period or extend the usage
period.

## Article 11 (Learning Records and Data)

① Learning Records of Non-members are stored solely on the user's device and cannot be
recovered once the application is deleted or the reset function within the Service is
used.

② Learning Records of Members are stored on the Company's servers and may be synchronized
across devices signed in to the same account.

③ The processing of personal data is governed by the separate **Privacy Policy**.

## Article 12 (Content and Data Sources)

① The historical price data used in the Service is constructed from the Financial Services
Commission's "Stock Price Information" dataset published on the Korean Public Data Portal,
and consists of historical daily prices based on previous-day closing prices.

② The Company does not warrant the accuracy, completeness, or timeliness of such data and
is not liable for consequences arising from errors in, or discontinuation of, the source
data.

③ Company names and ticker names shown in the Service are used to identify facts as of the
relevant period and do not imply any affiliation, sponsorship, or endorsement between
those companies and the Company.

## Article 13 (Not Investment Advice)

① All content in the Service is provided for **educational and informational purposes**
only and does not constitute a solicitation to buy or sell any financial investment
product, nor advice regarding investment decisions.

② Past chart patterns do not predict future prices. The patterns and cases presented in
the Service are facts verified by computation for specific historical periods only and do
not imply that the same pattern will lead to the same outcome in the future.

③ Any investment decision made on the basis of information obtained from the Service, and
its consequences, **rest entirely with the user**, and the Company is not liable for any
resulting loss.

## Article 14 (Intellectual Property)

① Intellectual property rights in the Service and in the software, design, question
construction, explanatory text, and trademarks contained therein belong to the Company.

② Users must not reproduce, distribute, transmit, publish, create derivative works from,
or otherwise use the subject matter of Paragraph 1, or allow third parties to do so,
without the Company's prior written consent.

③ Paragraph 1 does not assert any right over the public data itself as published by the
original providing institution.

## Article 15 (User Obligations)

Users must not:

- Reverse engineer, decompile, or disassemble the Service, or extract its source code
- Access the Service by automated means or collect data from it in bulk
- Reproduce and distribute, or commercially exploit, the content of the Service without
  authorization
- Use fraudulent means in the payment process
- Interfere with the stable operation of the Service
- Otherwise violate applicable law

## Article 16 (Limitation of Liability)

① The Company is relieved of liability where it cannot provide the Service due to causes
beyond its reasonable control, including natural disaster, war, power failure, or
interruption of telecommunications carrier services.

② The Company is not liable for service disruptions caused by reasons attributable to the
user.

③ The Company is not liable for a user's failure to achieve the learning outcomes they
expected from using the Service.

④ Nothing in these Terms excludes or limits the Company's liability for damage caused by
its **wilful misconduct or gross negligence**, or any other liability that cannot be
excluded or limited under applicable law.

## Article 17 (Dispute Resolution)

① The Company and users shall resolve any dispute arising in connection with the Service
through good-faith consultation.

② Where a dispute is not resolved through consultation, any action shall be brought before
the court having jurisdiction under the Civil Procedure Act of the Republic of Korea.

③ These Terms and the use of the Service are governed by the laws of the Republic of
Korea.

---

**Addendum**

These Terms take effect on July 21, 2026.
`

export const CHART_DRAW_TERMS_EN = [
  {
    version: '1.0',
    effective: '2026-07-21',
    summary: 'Initial publication',
    body: V1_0,
  },
]
